import torch


class GraphModule(torch.nn.Module):
    def forward(
        self,
        l_l_self_modules_bn1_buffers_running_mean_,
        l_l_self_modules_bn1_buffers_running_var_,
        l_l_self_modules_bn1_parameters_bias_,
        l_l_self_modules_bn1_parameters_weight_,
        l_l_self_modules_conv1_parameters_weight_,
        l_l_self_modules_fc_parameters_bias_,
        l_l_self_modules_fc_parameters_weight_,
        l_l_self_modules_layer1_modules_0_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer1_modules_0_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer1_modules_0_modules_bn1_parameters_bias_,
        l_l_self_modules_layer1_modules_0_modules_bn1_parameters_weight_,
        l_l_self_modules_layer1_modules_0_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer1_modules_0_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer1_modules_0_modules_bn2_parameters_bias_,
        l_l_self_modules_layer1_modules_0_modules_bn2_parameters_weight_,
        l_l_self_modules_layer1_modules_0_modules_conv1_parameters_weight_,
        l_l_self_modules_layer1_modules_0_modules_conv2_parameters_weight_,
        l_l_self_modules_layer1_modules_1_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer1_modules_1_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer1_modules_1_modules_bn1_parameters_bias_,
        l_l_self_modules_layer1_modules_1_modules_bn1_parameters_weight_,
        l_l_self_modules_layer1_modules_1_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer1_modules_1_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer1_modules_1_modules_bn2_parameters_bias_,
        l_l_self_modules_layer1_modules_1_modules_bn2_parameters_weight_,
        l_l_self_modules_layer1_modules_1_modules_conv1_parameters_weight_,
        l_l_self_modules_layer1_modules_1_modules_conv2_parameters_weight_,
        l_l_self_modules_layer2_modules_0_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer2_modules_0_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer2_modules_0_modules_bn1_parameters_bias_,
        l_l_self_modules_layer2_modules_0_modules_bn1_parameters_weight_,
        l_l_self_modules_layer2_modules_0_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer2_modules_0_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer2_modules_0_modules_bn2_parameters_bias_,
        l_l_self_modules_layer2_modules_0_modules_bn2_parameters_weight_,
        l_l_self_modules_layer2_modules_0_modules_conv1_parameters_weight_,
        l_l_self_modules_layer2_modules_0_modules_conv2_parameters_weight_,
        l_l_self_modules_layer2_modules_0_modules_downsample_modules_0_parameters_weight_,
        l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_buffers_running_mean_,
        l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_buffers_running_var_,
        l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_parameters_bias_,
        l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_parameters_weight_,
        l_l_self_modules_layer2_modules_1_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer2_modules_1_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer2_modules_1_modules_bn1_parameters_bias_,
        l_l_self_modules_layer2_modules_1_modules_bn1_parameters_weight_,
        l_l_self_modules_layer2_modules_1_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer2_modules_1_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer2_modules_1_modules_bn2_parameters_bias_,
        l_l_self_modules_layer2_modules_1_modules_bn2_parameters_weight_,
        l_l_self_modules_layer2_modules_1_modules_conv1_parameters_weight_,
        l_l_self_modules_layer2_modules_1_modules_conv2_parameters_weight_,
        l_l_self_modules_layer3_modules_0_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer3_modules_0_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer3_modules_0_modules_bn1_parameters_bias_,
        l_l_self_modules_layer3_modules_0_modules_bn1_parameters_weight_,
        l_l_self_modules_layer3_modules_0_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer3_modules_0_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer3_modules_0_modules_bn2_parameters_bias_,
        l_l_self_modules_layer3_modules_0_modules_bn2_parameters_weight_,
        l_l_self_modules_layer3_modules_0_modules_conv1_parameters_weight_,
        l_l_self_modules_layer3_modules_0_modules_conv2_parameters_weight_,
        l_l_self_modules_layer3_modules_0_modules_downsample_modules_0_parameters_weight_,
        l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_buffers_running_mean_,
        l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_buffers_running_var_,
        l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_parameters_bias_,
        l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_parameters_weight_,
        l_l_self_modules_layer3_modules_1_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer3_modules_1_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer3_modules_1_modules_bn1_parameters_bias_,
        l_l_self_modules_layer3_modules_1_modules_bn1_parameters_weight_,
        l_l_self_modules_layer3_modules_1_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer3_modules_1_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer3_modules_1_modules_bn2_parameters_bias_,
        l_l_self_modules_layer3_modules_1_modules_bn2_parameters_weight_,
        l_l_self_modules_layer3_modules_1_modules_conv1_parameters_weight_,
        l_l_self_modules_layer3_modules_1_modules_conv2_parameters_weight_,
        l_l_self_modules_layer4_modules_0_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer4_modules_0_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer4_modules_0_modules_bn1_parameters_bias_,
        l_l_self_modules_layer4_modules_0_modules_bn1_parameters_weight_,
        l_l_self_modules_layer4_modules_0_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer4_modules_0_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer4_modules_0_modules_bn2_parameters_bias_,
        l_l_self_modules_layer4_modules_0_modules_bn2_parameters_weight_,
        l_l_self_modules_layer4_modules_0_modules_conv1_parameters_weight_,
        l_l_self_modules_layer4_modules_0_modules_conv2_parameters_weight_,
        l_l_self_modules_layer4_modules_0_modules_downsample_modules_0_parameters_weight_,
        l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_buffers_running_mean_,
        l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_buffers_running_var_,
        l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_parameters_bias_,
        l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_parameters_weight_,
        l_l_self_modules_layer4_modules_1_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer4_modules_1_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer4_modules_1_modules_bn1_parameters_bias_,
        l_l_self_modules_layer4_modules_1_modules_bn1_parameters_weight_,
        l_l_self_modules_layer4_modules_1_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer4_modules_1_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer4_modules_1_modules_bn2_parameters_bias_,
        l_l_self_modules_layer4_modules_1_modules_bn2_parameters_weight_,
        l_l_self_modules_layer4_modules_1_modules_conv1_parameters_weight_,
        l_l_self_modules_layer4_modules_1_modules_conv2_parameters_weight_,
        l_l_x_,
    ):
        x = torch.conv2d(
            l_l_x_,
            l_l_self_modules_conv1_parameters_weight_,
            None,
            (2, 2),
            (3, 3),
            (1, 1),
            1,
        )
        l_l_x_ = l_l_self_modules_conv1_parameters_weight_ = None
        x_1 = torch.nn.functional.batch_norm(
            x,
            l_l_self_modules_bn1_buffers_running_mean_,
            l_l_self_modules_bn1_buffers_running_var_,
            l_l_self_modules_bn1_parameters_weight_,
            l_l_self_modules_bn1_parameters_bias_,
            False,
            0.1,
            1e-05,
        )
        x = (
            l_l_self_modules_bn1_buffers_running_mean_
        ) = (
            l_l_self_modules_bn1_buffers_running_var_
        ) = (
            l_l_self_modules_bn1_parameters_weight_
        ) = l_l_self_modules_bn1_parameters_bias_ = None
        x_2 = torch.nn.functional.relu(x_1, inplace=True)
        x_1 = None
        x_3 = torch.nn.functional.max_pool2d(
            x_2, 3, 2, 1, 1, ceil_mode=False, return_indices=False
        )
        x_2 = None
        x_4 = torch.conv2d(
            x_3,
            l_l_self_modules_layer1_modules_0_modules_conv1_parameters_weight_,
            None,
            (1, 1),
            (1, 1),
            (1, 1),
            1,
        )
        l_l_self_modules_layer1_modules_0_modules_conv1_parameters_weight_ = None
        x_5 = torch.nn.functional.batch_norm(
            x_4,
            l_l_self_modules_layer1_modules_0_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer1_modules_0_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer1_modules_0_modules_bn1_parameters_weight_,
            l_l_self_modules_layer1_modules_0_modules_bn1_parameters_bias_,
            False,
            0.1,
            1e-05,
        )
        x_4 = (
            l_l_self_modules_layer1_modules_0_modules_bn1_buffers_running_mean_
        ) = (
            l_l_self_modules_layer1_modules_0_modules_bn1_buffers_running_var_
        ) = (
            l_l_self_modules_layer1_modules_0_modules_bn1_parameters_weight_
        ) = l_l_self_modules_layer1_modules_0_modules_bn1_parameters_bias_ = None
        x_6 = torch.nn.functional.relu(x_5, inplace=True)
        x_5 = None
        x_7 = torch.conv2d(
            x_6,
            l_l_self_modules_layer1_modules_0_modules_conv2_parameters_weight_,
            None,
            (1, 1),
            (1, 1),
            (1, 1),
            1,
        )
        x_6 = l_l_self_modules_layer1_modules_0_modules_conv2_parameters_weight_ = None
        return (
            l_l_self_modules_fc_parameters_bias_,
            l_l_self_modules_fc_parameters_weight_,
            l_l_self_modules_layer1_modules_0_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer1_modules_0_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer1_modules_0_modules_bn2_parameters_bias_,
            l_l_self_modules_layer1_modules_0_modules_bn2_parameters_weight_,
            l_l_self_modules_layer1_modules_1_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer1_modules_1_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer1_modules_1_modules_bn1_parameters_bias_,
            l_l_self_modules_layer1_modules_1_modules_bn1_parameters_weight_,
            l_l_self_modules_layer1_modules_1_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer1_modules_1_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer1_modules_1_modules_bn2_parameters_bias_,
            l_l_self_modules_layer1_modules_1_modules_bn2_parameters_weight_,
            l_l_self_modules_layer1_modules_1_modules_conv1_parameters_weight_,
            l_l_self_modules_layer1_modules_1_modules_conv2_parameters_weight_,
            l_l_self_modules_layer2_modules_0_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer2_modules_0_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer2_modules_0_modules_bn1_parameters_bias_,
            l_l_self_modules_layer2_modules_0_modules_bn1_parameters_weight_,
            l_l_self_modules_layer2_modules_0_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer2_modules_0_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer2_modules_0_modules_bn2_parameters_bias_,
            l_l_self_modules_layer2_modules_0_modules_bn2_parameters_weight_,
            l_l_self_modules_layer2_modules_0_modules_conv1_parameters_weight_,
            l_l_self_modules_layer2_modules_0_modules_conv2_parameters_weight_,
            l_l_self_modules_layer2_modules_0_modules_downsample_modules_0_parameters_weight_,
            l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_buffers_running_mean_,
            l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_buffers_running_var_,
            l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_parameters_bias_,
            l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_parameters_weight_,
            l_l_self_modules_layer2_modules_1_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer2_modules_1_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer2_modules_1_modules_bn1_parameters_bias_,
            l_l_self_modules_layer2_modules_1_modules_bn1_parameters_weight_,
            l_l_self_modules_layer2_modules_1_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer2_modules_1_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer2_modules_1_modules_bn2_parameters_bias_,
            l_l_self_modules_layer2_modules_1_modules_bn2_parameters_weight_,
            l_l_self_modules_layer2_modules_1_modules_conv1_parameters_weight_,
            l_l_self_modules_layer2_modules_1_modules_conv2_parameters_weight_,
            l_l_self_modules_layer3_modules_0_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer3_modules_0_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer3_modules_0_modules_bn1_parameters_bias_,
            l_l_self_modules_layer3_modules_0_modules_bn1_parameters_weight_,
            l_l_self_modules_layer3_modules_0_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer3_modules_0_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer3_modules_0_modules_bn2_parameters_bias_,
            l_l_self_modules_layer3_modules_0_modules_bn2_parameters_weight_,
            l_l_self_modules_layer3_modules_0_modules_conv1_parameters_weight_,
            l_l_self_modules_layer3_modules_0_modules_conv2_parameters_weight_,
            l_l_self_modules_layer3_modules_0_modules_downsample_modules_0_parameters_weight_,
            l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_buffers_running_mean_,
            l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_buffers_running_var_,
            l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_parameters_bias_,
            l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_parameters_weight_,
            l_l_self_modules_layer3_modules_1_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer3_modules_1_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer3_modules_1_modules_bn1_parameters_bias_,
            l_l_self_modules_layer3_modules_1_modules_bn1_parameters_weight_,
            l_l_self_modules_layer3_modules_1_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer3_modules_1_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer3_modules_1_modules_bn2_parameters_bias_,
            l_l_self_modules_layer3_modules_1_modules_bn2_parameters_weight_,
            l_l_self_modules_layer3_modules_1_modules_conv1_parameters_weight_,
            l_l_self_modules_layer3_modules_1_modules_conv2_parameters_weight_,
            l_l_self_modules_layer4_modules_0_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer4_modules_0_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer4_modules_0_modules_bn1_parameters_bias_,
            l_l_self_modules_layer4_modules_0_modules_bn1_parameters_weight_,
            l_l_self_modules_layer4_modules_0_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer4_modules_0_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer4_modules_0_modules_bn2_parameters_bias_,
            l_l_self_modules_layer4_modules_0_modules_bn2_parameters_weight_,
            l_l_self_modules_layer4_modules_0_modules_conv1_parameters_weight_,
            l_l_self_modules_layer4_modules_0_modules_conv2_parameters_weight_,
            l_l_self_modules_layer4_modules_0_modules_downsample_modules_0_parameters_weight_,
            l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_buffers_running_mean_,
            l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_buffers_running_var_,
            l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_parameters_bias_,
            l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_parameters_weight_,
            l_l_self_modules_layer4_modules_1_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer4_modules_1_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer4_modules_1_modules_bn1_parameters_bias_,
            l_l_self_modules_layer4_modules_1_modules_bn1_parameters_weight_,
            l_l_self_modules_layer4_modules_1_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer4_modules_1_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer4_modules_1_modules_bn2_parameters_bias_,
            l_l_self_modules_layer4_modules_1_modules_bn2_parameters_weight_,
            l_l_self_modules_layer4_modules_1_modules_conv1_parameters_weight_,
            l_l_self_modules_layer4_modules_1_modules_conv2_parameters_weight_,
            x_3,
            x_7,
        )
