import torch


class GraphModule(torch.nn.Module):
    def forward(
        self,
        l_l_self_modules_fc_parameters_bias_,
        l_l_self_modules_fc_parameters_weight_,
        l_l_self_modules_layer1_modules_0_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer1_modules_0_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer1_modules_0_modules_bn2_parameters_bias_,
        l_l_self_modules_layer1_modules_0_modules_bn2_parameters_weight_,
        l_l_self_modules_layer1_modules_1_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer1_modules_1_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer1_modules_1_modules_bn1_parameters_bias_,
        l_l_self_modules_layer1_modules_1_modules_bn1_parameters_weight_,
        l_l_self_modules_layer1_modules_1_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer1_modules_1_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer1_modules_1_modules_bn2_parameters_bias_,
        l_l_self_modules_layer1_modules_1_modules_bn2_parameters_weight_,
        l_l_self_modules_layer1_modules_1_modules_conv1_parameters_weight_,
        l_l_self_modules_layer1_modules_1_modules_conv2_parameters_weight_,
        l_l_self_modules_layer2_modules_0_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer2_modules_0_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer2_modules_0_modules_bn1_parameters_bias_,
        l_l_self_modules_layer2_modules_0_modules_bn1_parameters_weight_,
        l_l_self_modules_layer2_modules_0_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer2_modules_0_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer2_modules_0_modules_bn2_parameters_bias_,
        l_l_self_modules_layer2_modules_0_modules_bn2_parameters_weight_,
        l_l_self_modules_layer2_modules_0_modules_conv1_parameters_weight_,
        l_l_self_modules_layer2_modules_0_modules_conv2_parameters_weight_,
        l_l_self_modules_layer2_modules_0_modules_downsample_modules_0_parameters_weight_,
        l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_buffers_running_mean_,
        l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_buffers_running_var_,
        l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_parameters_bias_,
        l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_parameters_weight_,
        l_l_self_modules_layer2_modules_1_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer2_modules_1_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer2_modules_1_modules_bn1_parameters_bias_,
        l_l_self_modules_layer2_modules_1_modules_bn1_parameters_weight_,
        l_l_self_modules_layer2_modules_1_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer2_modules_1_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer2_modules_1_modules_bn2_parameters_bias_,
        l_l_self_modules_layer2_modules_1_modules_bn2_parameters_weight_,
        l_l_self_modules_layer2_modules_1_modules_conv1_parameters_weight_,
        l_l_self_modules_layer2_modules_1_modules_conv2_parameters_weight_,
        l_l_self_modules_layer3_modules_0_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer3_modules_0_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer3_modules_0_modules_bn1_parameters_bias_,
        l_l_self_modules_layer3_modules_0_modules_bn1_parameters_weight_,
        l_l_self_modules_layer3_modules_0_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer3_modules_0_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer3_modules_0_modules_bn2_parameters_bias_,
        l_l_self_modules_layer3_modules_0_modules_bn2_parameters_weight_,
        l_l_self_modules_layer3_modules_0_modules_conv1_parameters_weight_,
        l_l_self_modules_layer3_modules_0_modules_conv2_parameters_weight_,
        l_l_self_modules_layer3_modules_0_modules_downsample_modules_0_parameters_weight_,
        l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_buffers_running_mean_,
        l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_buffers_running_var_,
        l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_parameters_bias_,
        l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_parameters_weight_,
        l_l_self_modules_layer3_modules_1_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer3_modules_1_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer3_modules_1_modules_bn1_parameters_bias_,
        l_l_self_modules_layer3_modules_1_modules_bn1_parameters_weight_,
        l_l_self_modules_layer3_modules_1_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer3_modules_1_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer3_modules_1_modules_bn2_parameters_bias_,
        l_l_self_modules_layer3_modules_1_modules_bn2_parameters_weight_,
        l_l_self_modules_layer3_modules_1_modules_conv1_parameters_weight_,
        l_l_self_modules_layer3_modules_1_modules_conv2_parameters_weight_,
        l_l_self_modules_layer4_modules_0_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer4_modules_0_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer4_modules_0_modules_bn1_parameters_bias_,
        l_l_self_modules_layer4_modules_0_modules_bn1_parameters_weight_,
        l_l_self_modules_layer4_modules_0_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer4_modules_0_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer4_modules_0_modules_bn2_parameters_bias_,
        l_l_self_modules_layer4_modules_0_modules_bn2_parameters_weight_,
        l_l_self_modules_layer4_modules_0_modules_conv1_parameters_weight_,
        l_l_self_modules_layer4_modules_0_modules_conv2_parameters_weight_,
        l_l_self_modules_layer4_modules_0_modules_downsample_modules_0_parameters_weight_,
        l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_buffers_running_mean_,
        l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_buffers_running_var_,
        l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_parameters_bias_,
        l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_parameters_weight_,
        l_l_self_modules_layer4_modules_1_modules_bn1_buffers_running_mean_,
        l_l_self_modules_layer4_modules_1_modules_bn1_buffers_running_var_,
        l_l_self_modules_layer4_modules_1_modules_bn1_parameters_bias_,
        l_l_self_modules_layer4_modules_1_modules_bn1_parameters_weight_,
        l_l_self_modules_layer4_modules_1_modules_bn2_buffers_running_mean_,
        l_l_self_modules_layer4_modules_1_modules_bn2_buffers_running_var_,
        l_l_self_modules_layer4_modules_1_modules_bn2_parameters_bias_,
        l_l_self_modules_layer4_modules_1_modules_bn2_parameters_weight_,
        l_l_self_modules_layer4_modules_1_modules_conv1_parameters_weight_,
        l_l_self_modules_layer4_modules_1_modules_conv2_parameters_weight_,
        x_3,
        x_7,
    ):
        x_8 = torch.nn.functional.batch_norm(
            x_7,
            l_l_self_modules_layer1_modules_0_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer1_modules_0_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer1_modules_0_modules_bn2_parameters_weight_,
            l_l_self_modules_layer1_modules_0_modules_bn2_parameters_bias_,
            False,
            0.1,
            1e-05,
        )
        x_7 = (
            l_l_self_modules_layer1_modules_0_modules_bn2_buffers_running_mean_
        ) = (
            l_l_self_modules_layer1_modules_0_modules_bn2_buffers_running_var_
        ) = (
            l_l_self_modules_layer1_modules_0_modules_bn2_parameters_weight_
        ) = l_l_self_modules_layer1_modules_0_modules_bn2_parameters_bias_ = None
        x_8 += x_3
        x_9 = x_8
        x_8 = x_3 = None
        x_10 = torch.nn.functional.relu(x_9, inplace=True)
        x_9 = None
        x_11 = torch.conv2d(
            x_10,
            l_l_self_modules_layer1_modules_1_modules_conv1_parameters_weight_,
            None,
            (1, 1),
            (1, 1),
            (1, 1),
            1,
        )
        l_l_self_modules_layer1_modules_1_modules_conv1_parameters_weight_ = None
        x_12 = torch.nn.functional.batch_norm(
            x_11,
            l_l_self_modules_layer1_modules_1_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer1_modules_1_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer1_modules_1_modules_bn1_parameters_weight_,
            l_l_self_modules_layer1_modules_1_modules_bn1_parameters_bias_,
            False,
            0.1,
            1e-05,
        )
        x_11 = (
            l_l_self_modules_layer1_modules_1_modules_bn1_buffers_running_mean_
        ) = (
            l_l_self_modules_layer1_modules_1_modules_bn1_buffers_running_var_
        ) = (
            l_l_self_modules_layer1_modules_1_modules_bn1_parameters_weight_
        ) = l_l_self_modules_layer1_modules_1_modules_bn1_parameters_bias_ = None
        x_13 = torch.nn.functional.relu(x_12, inplace=True)
        x_12 = None
        x_14 = torch.conv2d(
            x_13,
            l_l_self_modules_layer1_modules_1_modules_conv2_parameters_weight_,
            None,
            (1, 1),
            (1, 1),
            (1, 1),
            1,
        )
        x_13 = l_l_self_modules_layer1_modules_1_modules_conv2_parameters_weight_ = None
        x_15 = torch.nn.functional.batch_norm(
            x_14,
            l_l_self_modules_layer1_modules_1_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer1_modules_1_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer1_modules_1_modules_bn2_parameters_weight_,
            l_l_self_modules_layer1_modules_1_modules_bn2_parameters_bias_,
            False,
            0.1,
            1e-05,
        )
        x_14 = (
            l_l_self_modules_layer1_modules_1_modules_bn2_buffers_running_mean_
        ) = (
            l_l_self_modules_layer1_modules_1_modules_bn2_buffers_running_var_
        ) = (
            l_l_self_modules_layer1_modules_1_modules_bn2_parameters_weight_
        ) = l_l_self_modules_layer1_modules_1_modules_bn2_parameters_bias_ = None
        return (
            l_l_self_modules_fc_parameters_bias_,
            l_l_self_modules_fc_parameters_weight_,
            l_l_self_modules_layer2_modules_0_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer2_modules_0_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer2_modules_0_modules_bn1_parameters_bias_,
            l_l_self_modules_layer2_modules_0_modules_bn1_parameters_weight_,
            l_l_self_modules_layer2_modules_0_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer2_modules_0_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer2_modules_0_modules_bn2_parameters_bias_,
            l_l_self_modules_layer2_modules_0_modules_bn2_parameters_weight_,
            l_l_self_modules_layer2_modules_0_modules_conv1_parameters_weight_,
            l_l_self_modules_layer2_modules_0_modules_conv2_parameters_weight_,
            l_l_self_modules_layer2_modules_0_modules_downsample_modules_0_parameters_weight_,
            l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_buffers_running_mean_,
            l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_buffers_running_var_,
            l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_parameters_bias_,
            l_l_self_modules_layer2_modules_0_modules_downsample_modules_1_parameters_weight_,
            l_l_self_modules_layer2_modules_1_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer2_modules_1_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer2_modules_1_modules_bn1_parameters_bias_,
            l_l_self_modules_layer2_modules_1_modules_bn1_parameters_weight_,
            l_l_self_modules_layer2_modules_1_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer2_modules_1_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer2_modules_1_modules_bn2_parameters_bias_,
            l_l_self_modules_layer2_modules_1_modules_bn2_parameters_weight_,
            l_l_self_modules_layer2_modules_1_modules_conv1_parameters_weight_,
            l_l_self_modules_layer2_modules_1_modules_conv2_parameters_weight_,
            l_l_self_modules_layer3_modules_0_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer3_modules_0_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer3_modules_0_modules_bn1_parameters_bias_,
            l_l_self_modules_layer3_modules_0_modules_bn1_parameters_weight_,
            l_l_self_modules_layer3_modules_0_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer3_modules_0_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer3_modules_0_modules_bn2_parameters_bias_,
            l_l_self_modules_layer3_modules_0_modules_bn2_parameters_weight_,
            l_l_self_modules_layer3_modules_0_modules_conv1_parameters_weight_,
            l_l_self_modules_layer3_modules_0_modules_conv2_parameters_weight_,
            l_l_self_modules_layer3_modules_0_modules_downsample_modules_0_parameters_weight_,
            l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_buffers_running_mean_,
            l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_buffers_running_var_,
            l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_parameters_bias_,
            l_l_self_modules_layer3_modules_0_modules_downsample_modules_1_parameters_weight_,
            l_l_self_modules_layer3_modules_1_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer3_modules_1_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer3_modules_1_modules_bn1_parameters_bias_,
            l_l_self_modules_layer3_modules_1_modules_bn1_parameters_weight_,
            l_l_self_modules_layer3_modules_1_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer3_modules_1_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer3_modules_1_modules_bn2_parameters_bias_,
            l_l_self_modules_layer3_modules_1_modules_bn2_parameters_weight_,
            l_l_self_modules_layer3_modules_1_modules_conv1_parameters_weight_,
            l_l_self_modules_layer3_modules_1_modules_conv2_parameters_weight_,
            l_l_self_modules_layer4_modules_0_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer4_modules_0_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer4_modules_0_modules_bn1_parameters_bias_,
            l_l_self_modules_layer4_modules_0_modules_bn1_parameters_weight_,
            l_l_self_modules_layer4_modules_0_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer4_modules_0_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer4_modules_0_modules_bn2_parameters_bias_,
            l_l_self_modules_layer4_modules_0_modules_bn2_parameters_weight_,
            l_l_self_modules_layer4_modules_0_modules_conv1_parameters_weight_,
            l_l_self_modules_layer4_modules_0_modules_conv2_parameters_weight_,
            l_l_self_modules_layer4_modules_0_modules_downsample_modules_0_parameters_weight_,
            l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_buffers_running_mean_,
            l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_buffers_running_var_,
            l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_parameters_bias_,
            l_l_self_modules_layer4_modules_0_modules_downsample_modules_1_parameters_weight_,
            l_l_self_modules_layer4_modules_1_modules_bn1_buffers_running_mean_,
            l_l_self_modules_layer4_modules_1_modules_bn1_buffers_running_var_,
            l_l_self_modules_layer4_modules_1_modules_bn1_parameters_bias_,
            l_l_self_modules_layer4_modules_1_modules_bn1_parameters_weight_,
            l_l_self_modules_layer4_modules_1_modules_bn2_buffers_running_mean_,
            l_l_self_modules_layer4_modules_1_modules_bn2_buffers_running_var_,
            l_l_self_modules_layer4_modules_1_modules_bn2_parameters_bias_,
            l_l_self_modules_layer4_modules_1_modules_bn2_parameters_weight_,
            l_l_self_modules_layer4_modules_1_modules_conv1_parameters_weight_,
            l_l_self_modules_layer4_modules_1_modules_conv2_parameters_weight_,
            x_10,
            x_15,
        )
